# Generated by Django 4.0 on 2022-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('mobno', models.CharField(default='', max_length=50)),
                ('uid', models.CharField(default='', max_length=50)),
                ('imagelink', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
