# Generated by Django 4.0 on 2022-04-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapi', '0002_tokan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='mobno',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='imagelink',
            new_name='pic',
        ),
        migrations.AddField(
            model_name='userdata',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
    ]
